### ISSUE TITLE
Html generated links have nofollow?

### ISSUE THREAD

**Issue by NetTecture** [xoofx/markdig#756] opened 2023-11-29 23:40 UTC
Any reference how to control that? Would like to not have nofollow for links that are - well - internal (and some external).

**Comment by xoofx** [comment] 2023-11-30 07:41
I don't think this is enabled by default. How do you create your `MarkdownPipelineBuilder`?

**Comment by NetTecture** [comment] 2023-12-01 22:51
static readonly MarkdownPipeline pipeline = new MarkdownPipelineBuilder()
        .UseAdvancedExtensions()
        .UseAutoLinks()
        .UseBootstrap()
        .Build();

    public static string RenderToHtml(string text, bool inline = false)
    {
        if (inline)
        {
            return RenderToHtmlInline(text);
        }
        return Markdown.ToHtml(text, pipeline);
    }

    public static string RenderToHtmlInline(string text)
    {
        var document = Markdown.Parse(text, pipeline);

        StringWriter writer = new();
        var renderer = new HtmlRenderer(writer)
        {
            ImplicitParagraph = true // note this change
        };
        pipeline.Setup(renderer);

        renderer.Render(document); // using the renderer directly
        writer.Flush();
        string html = writer.ToString();
        html = html.Replace(" rel=\"nofollow\"", "");
        return html;
    }
    
    This is literally the complete code for my render pipeline at the moment.

**Comment by xoofx** [comment] 2023-12-12 18:21
I cannot see any usage of nofollow in the current codebase. I just created an exe with the latest Markdig 0.33 and I'm getting the correct output:

```c#
internal class Program
{
    static void Main(string[] args)
    {
        MarkdownPipeline pipeline = new MarkdownPipelineBuilder()
            .UseAdvancedExtensions()
            .UseAutoLinks()
            .UseBootstrap()
            .Build();

        var document = Markdown.Parse("Hello with a link [Hello](https://google.com)", pipeline);
        var html = document.ToHtml(pipeline);

        Console.WriteLine(html);
    }
}
```

Outputs:

```
<p>Hello with a link <a href="https://google.com">Hello</a></p>
```

So closing this bug as invalid because it is not reproduced.

**Closed by xoofx** 2023-12-12 18:21 UTC
Labels: invalid
